### ISSUE TITLE
cant't accach the devices (!! process pid or name must be specified)

### ISSUE THREAD

**Issue by ideaseek** [swdunlop/AndBug#16]
the adb command is right, but i can't attach the devices.

abi@abi-desktop:~/AndBug$ PYTHONPATH=lib ./andbug  shell  –p 1484
!! process pid or name must be specified

**Comment by xiaozxy** [comment]
me too...

**Comment by swdunlop** [comment]
You must ensure that the process is configured to enable debugging, and the device.
