### ISSUE TITLE
error constant in code?

### ISSUE THREAD

**Issue by CzBiX** [swdunlop/AndBug#4]
in andbug.vm.Thread.suspend
...
conn.request(0x0B01, buf.data())
why it's not 0x0B02? mistake?

**Comment by swdunlop** [comment]
I'll look into it next week -- defcon qualifiers this weekend are consuming all my cpu cycles :)

**Comment by swdunlop** [comment]
Thank you for the bugreport, @CzBiX -- vm.py was definitely wrong, here.  I have fixed the constant to 0xb02 and reviewed all other uses of conn.request for errors, along with some cleanups from my personal branch.  See the following for changes:

https://github.com/swdunlop/AndBug/commit/436f7236ae9ea39bb6222e0ad62fe304dc475e24
